version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve  --config _config-development.yml -H 0.0.0.0 -t
    # command: /bin/bash # use `docker-compose exec jekyll /bin/bash`
